; Config file for a disease simulation

[global]
simulation_name = my_simulation    ; A identifier for the simulation
num_populations = 4                ; total number of populations to model
simulation_runs = 5                ; total number of runs 

[disease]                          ; Global disease configuration
name = "Corona"                    ; Name of the disease
duration =   7                     ; Days a person is infectious 
transmissibility = 0.3             ; Probability of the disease being 
                                   ;   transmitted on contact
                                   ;   (0.0 = 0%, 1.0 = 100%)

; For each population a section is added
[population_1]                     ; Use "population_" plus number        
name = Deggendorf                  ; Name of the population, e.g.,
                                   ;   a city or neighbourhood  
size = 30000                       ; Number of persons in the population 4000
vaccination_rate = 0.9             ; Fraction of persons vaccinated 
                                   ;   (0.0 = 0%, 1.0 = 100%)
patient_0 = true                   ; If true, the population starts 
                                   ;   with a single infectious person          

; the following is only an example showing you how this input file 
; may be used in an extended setting. You are not required to implement 
; multiple populations as part of your course project.
[population_2]                     ; see population_1
name = Regensburg
size = 15000           
vaccination_rate = 0.0  
patient_0 = false       

[population_3]
name = Zwiesel  
size = 1500           
vaccination_rate = 0.0  
patient_0 = false       

[population_4]
name = Delhi
size = 30000
vaccination_rate = 0.4
patient_0 = true

[population_5]
name = Rome
size = 30000
vaccination_rate = 0.5
patient_0 = true

[population_6]
name = Moscow
size = 30000
vaccination_rate = 0.6
patient_0 = true

[population_8]
name = Hong Kong
size = 30000
vaccination_rate = 0.3
patient_0 = true